spring:
  application:
    name: shcoolManager
  datasource:
    url: jdbc:mysql://localhost:3308/shcool_manager
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
